kind: DaemonSet
replicaCount: 1
image:
  repository: fluent/fluent-bit
testFramework:
  enabled: true
  namespace: fluentbit
  image:
    repository: busybox
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        # Parser docker_no_time
        Parser time_parser

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On


  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_Tag_Prefix kube.var.log.containers
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name    multiline
        Match   kube.life-insurance.*
        multiline.parser multiline_safineh    

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-es-http.elasticsearch
        HTTP_User elastic
        HTTP_Passwd cvp960sN2b61ib5FU2k1j8Fo
        tls On
        tls.verify Off
        Suppress_Type_Name On
        Port 9200
        Logstash_Format Off
        Index kubernetes 
        Retry_Limit False
        Trace_Error On
        Replace_Dots On


logLevel: Error
