---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange
  namespace: exchange
  labels:
    app: exchange
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
      - name: exchange
        image: your-registry/crypto-exchange:v1
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: DEBUG
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: DATABASE_USER
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: DATABASE_PORT
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exchange-secret
              key: DATABASE_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: exchange-secret
              key: SECRET_KEY
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: exchange-secret
              key: API_KEY
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: MINIO_ENDPOINT
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: exchange-secret
              key: MINIO_SECRET_KEY
        - name: MINIO_USE_SSL
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: MINIO_USE_SSL
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: exchange
  namespace: crypto-exchange
  labels:
    app: exchange
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: exchange
